### ISSUE TITLE
Exiting combat in a WoD dungeon - error about cooldown

### ISSUE THREAD

**Issue by ceylina** [nebularg/Parrot2#1]
### What steps will reproduce the problem?
After exiting dungeon (shadowmoon burial grounds)

### What version of Parrot are you using?
2.0.0

### Do you have an error log of what happened?

1x Parrot\Data\Cooldowns.lua:130: bad argument #1 to 'format' (string expected, got nil)
[C]: in function `format'
Parrot\Data\Cooldowns.lua:130: in function `?'
...non\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...non\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'

Locals:
nil

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

Does the argument passed into that section need a check to verify it is not nil?

**Comment by nebularg** [comment]
That's pretty weird, I'll add a nil check, What class were you playing?

**Comment by ceylina** [comment]
Was on my hunter, BM. Could have been any number of cooldowns too, I didn't really check.
