### ISSUE TITLE
Just putting this script too long error FYI

### ISSUE THREAD

**Issue by ceylina** [nebularg/Parrot2#10]
This is the second time I have had this happen and it is nothing I can narrow down as to exactly when

v2.0.3-3-g1dd53b4

1x Parrot\Code\Display-Display.lua:469: script ran too long
Parrot\Code\Display-Display.lua:469: in function `OnUpdate'
Parrot\Code\Display-Display.lua:403: in function`ShowMessage'
Parrot\Code\CombatEvents.lua:2160: in function <Parrot\Code\CombatEvents.lua:2015>
Parrot\Code\CombatEvents.lua:2173: in function <Parrot\Code\CombatEvents.lua:2170>

Locals:

**Comment by nebularg** [comment]
For now setting a low spell throttle on skills helps prevent it. I'll probably have to force throttle things, AOE on many mobs usually results in an error for me 😞

**Comment by ceylina** [comment]
closing since this hasn't happened in months now
