### ISSUE TITLE
[SOD] Something is wrong with the 'icon' code in CombatEvents.lua making the app crash

### ISSUE THREAD

**Issue by Larzie** [nebularg/Parrot2#108]
Since the new phase (phase 3). Something is wrong with the icon code in CombatEvents.lua. The codechanges below make the addon work again, but it removes the icons from the scroll areas ofc.

Change line 2066 from this:
          icon = icon(info)

To this:
      -- icon = icon(info)
      
Do you see why icon(info) doesn't work anymore?

Thank you so much <3

**Comment by Blueing** [comment]
I replaced GetItemIcon with GetItemIconByID in Auras.lua and didnt run in an error sinde then. Idk if its the right fix, but for me it seems to work

**Comment by nebularg** [comment]
Thanks, I'll push some quick fixes for this and work on combining the classic/retail version since it looks like a lot of the cruft needed for classic era has gone away

**Comment by nteetor** [comment]
Awesome, thank you. I'll reply if I see the problem again.
