### ISSUE TITLE
Parrot 2 RE-Enabling Floating combat text after restart or reload

### ISSUE THREAD

**Issue by JustDenDimi** [nebularg/Parrot2#11]
### What steps will reproduce the problem?
1.  Install AdvancedInterfaceOptions (AIO)
2.  Install Parrot 2 (Not Parrot 1, works fine there)
3.  Disable Floating combat text in AIO
4. Reload or restart WoW

### What version of Parrot are you using?
v2.0.3

### Do you have an error log of what happened?
No, no error, just an option that gets overwritten by parrot 2.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
enGB, version 7.0.3 latest update as of 27/09/2016.
Parrot 2 constantly re-enables the floating combat text after a reload or a WoW restart.
I disable the floating combat text with either the console command or AdvancedInterfaceOptions.
I do not have this problem with Parrot 1, so I use that now.

**Comment by nebularg** [comment]
Uncheck the options in Parrot.

![](http://i.imgur.com/T1B7xON.jpg)
