### ISSUE TITLE
Current code expects "triggers2" to be a table, was number in my SavedVar

### ISSUE THREAD

**Issue by Nulgar** [nebularg/Parrot2#110]
### What steps will reproduce the problem?
After updating to the latest version from a previous one, I got various Lua errors complaining about the variable "triggers2" not being a table. Checked the SavedVar, it had a value of 0. Deleting the line fixed the issue.

### What version of Parrot are you using?
v2.2.3

### Do you have an error log of what happened?
Bit too lazy to reverse the issue to copy&paste the Lua error :)

**Comment by nebularg** [comment]
Should be fixed, thanks
