### ISSUE TITLE
triggers2 Save Var LUA error.

### ISSUE THREAD

**Issue by Freakatsu** [nebularg/Parrot2#111]
### What steps will reproduce the problem?
1. Same error as the other person, just pasting you the LUA since he didnt.
2.  Deleting the triggers2 lines and all profiles from SaveVariables file does fix it.

### What version of Parrot are you using?
2.2.3

### Do you have an error log of what happened?

22x Parrot/Code/Triggers.lua:803: bad argument #1 to '(for generator)' (table expected, got number)
[string "=[C]"]: in function `(for generator)'
[string "@Parrot/Code/Triggers.lua"]:803: in function <Parrot/Code/Triggers.lua:797>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
enGB

**Comment by nebularg** [comment]
Should be fixed, thanks
