### ISSUE TITLE
Please help tp update Parrot2 for 11.0.2.56110. THANKS

### ISSUE THREAD

**Issue by z78929999** [nebularg/Parrot2#118]
### What steps will reproduce the problem?
1.  
2.  
3.  

### What version of Parrot are you using?
v2.2.3 for WOW CN11.0.2.56110

### Do you have an error log of what happened?

266x Parrot/Code/TriggerConditions.lua:60: attempt to call method 'OnTriggerCondition' (a nil value)
[string "@Parrot/Code/TriggerConditions.lua"]:60: in function `FirePrimaryTriggerCondition'
[string "@Parrot/Code/TriggerConditions.lua"]:274: in function `HandleCombatlogEvent'
[string "@Parrot/Code/Parrot.lua"]:311: in function <Parrot/Code/Parrot.lua:308>
[string "=[C]"]: ?
[string "@Accountant/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "Parrot_TriggerConditions"
 orderedModules = <table> {
 }
 baseName = "Parrot"
 combatLogEvents = <table> {
 }
 enabledState = true
 defaultModuleState = true
 moduleName = "TriggerConditions"
}
name = "Aura fade"
arg = <table> {
 spellId = 85739
 dstGUID = "Player-1933-068112DD"
 auraType = "BUFF"
 spellName = "旋風斬"
}
uid = 1
(*temporary) = nil
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "Parrot_Triggers"
 orderedModules = <table> {
 }
 enabledState = true
 baseName = "Parrot"
 defaultModuleState = true
 moduleName = "Triggers"
}
(*temporary) = "Aura fade"
(*temporary) = <table> {
 spellId = 85739
 dstGUID = "Player-1933-068112DD"
 auraType = "BUFF"
 spellName = "旋風斬"
}
(*temporary) = 1
(*temporary) = "attempt to call method 'OnTriggerCondition' (a nil value)"
Parrot_Triggers = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "Parrot_Triggers"
 orderedModules = <table> {
 }
 enabledState = true
 baseName = "Parrot"
 defaultModuleState = true
 moduleName = "Triggers"
}
conditions = <table> {
 Item buff fade = <table> {
 }
 Unit health = <table> {
 }
 Outgoing damage = <table> {
 }
 Incoming cast = <table> {
 }
 Aura fade = <table> {
 }
 Outgoing cast = <table> {
 }
 Incoming crit = <table> {
 }
 Incoming damage = <table> {
 }
 Cast started = <table> {
 }
 Item cooldown ready = <table> {
 }
 Outgoing miss = <table> {
 }
 Outgoing crit = <table> {
 }
 Leave combat = <table> {
 }
 Aura stack gain = <table> {
 }
 Aura gain = <table> {
 }
 Unit power = <table> {
 }
 Incoming miss = <table> {
 }
 Spell ready = <table> {
 }
 Item buff gain = <table> {
 }
 Enter combat = <table> {
 }
}

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
WOW CN11.0.2.56110
Yesterday it was still works for 11.0.0.56008.... but after today game updates. which can not anymore.....

**Comment by Halbarath** [comment]
Might be related to this:
https://warcraft.wiki.gg/wiki/Patch_10.2.6/API_changes

**Comment by Halbarath** [comment]
Might be related to this:
https://warcraft.wiki.gg/wiki/Patch_11.0.0/API_changes

**Comment by jockeeric** [comment]
Looks like it, addon started working again when I updated it. However it seems as if the included "libsink" also needs to be updated.

**Comment by nebularg** [comment]
Should be good to go again

**Comment by z78929999** [comment]
thanks a lot for the comments and update !!
