### ISSUE TITLE
Feature request: shortened versions of numbers

### ISSUE THREAD

**Issue by mmdet3** [nebularg/Parrot2#124]
Given how big numbers are getting even at the very start of TWW, it'd be great if Parrot 2 had an option to condense numbers of combat abilities. For example, instead of showing a heal of 1132492, I'd prefer to see it as 1.13M etc. Ideally this would be configurable, but even just a basic shortening would be super helpful. 

Alternatively, maybe adding commas might help so that heal displayed as 1,132,492 (which is also a bit easier to read).

**Comment by nebularg** [comment]
Have you tried using the options under events?

![image](https://github.com/user-attachments/assets/da930731-2ed5-4392-b3c4-0fdbcca53743)

**Comment by mmdet3** [comment]
D'oh. Yes that's what I was looking for - right under my nose the whole time. Thanks!

**Comment by mmdet3** [comment]
Closing

**Comment by nebularg** [comment]
Cheers, wasn't sure if there was something that needed to be updated with it
