### ISSUE TITLE
Request: toggle to disable in pvp (BG/Arena) like how disable in raid option is

### ISSUE THREAD

**Issue by ceylina** [nebularg/Parrot2#13]
Can you add an option to disable in pvp battlegrounds and /or arenas? Similar to how you have for disabling in raids? I get most of the script ran too long errors while in BGs and it would be super if I could have parrot off in pvp situations.

**Comment by Pandha** [comment]
where is this option for raids? my addon disabled it for mythic raids :(

**Comment by ceylina** [comment]
It's for event filtering not the entire addon. I've manually added it and it helps so hopefully we can get this
