### ISSUE TITLE
v2.0.4-6-g111eab0 - installing via curse client fails to unzip

### ISSUE THREAD

**Issue by ceylina** [nebularg/Parrot2#16]
Reposting this here 

The curse client fails to unzip this when installing or updating. Something funky is going on with v2.0.4-6-g111eab0

I can manually download and extract it fine but if I try and go through the curse client it fails at unzipping. Never seen this one before

**Comment by ceylina** [comment]
2.0.5 is having this to. Something is up with the zip file.

**Comment by nebularg** [comment]
can you pull the curse log and paste the relevant part? should be somewhere in `%AppData%\Curse Client\Logs`

**Comment by ceylina** [comment]
I think this is it 


{
  "timestamp": "2017-04-01T23:24:17.746Z",
  "level": "Info",
  "thread": 6364,
  "memory": 134296.0,
  "message": "[UI] Setting addon instances",
  "data": {
    "addonInstanceCount": 77,
    "areAddonInstancesLoaded": true,
    "isScanning": false
  }
},
{
  "timestamp": "2017-04-01T23:24:25.6230197Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134244.0,
  "message": "[AddOnServiceClient] Making service call: GetAddOnFile() addonID: 101768 fileID: 2401210"
},
{
  "timestamp": "2017-04-01T23:24:25.7451517Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134260.0,
  "message": "[AddonInstalltask] Installing file - FileId: 2401210, FileName: v2.0.5, DownloadURL: https://addons.cursecdn.com/files/2401/210/Parrot-v2.0.5.zip"
},
{
  "timestamp": "2017-04-01T23:24:25.7471556Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134260.0,
  "message": "[AddOnServiceClient] Making service call: GetAddOns()"
},
{
  "timestamp": "2017-04-01T23:24:25.8756249Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134264.0,
  "message": "Downloading: https://addons.cursecdn.com/files/2401/210/Parrot-v2.0.5.zip to C:\\Users\\Ceylina\\AppData\\Local\\Temp\\Curse Client\\4CF5799E232C4E68BD6E532ABEE391D4\\4.zip"
},
{
  "timestamp": "2017-04-01T23:24:25.613Z",
  "level": "Info",
  "thread": 6364,
  "memory": 134264.0,
  "message": "[UI] AddonActions->installAddon 7da8e1bc-fe18-4aa5-ba42-6f061892b8a9 - 101768"
},
{
  "timestamp": "2017-04-01T23:24:28.800942Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134184.0,
  "message": "Attempt #1 of 3 on UnzipFileInstallTask.Run -> ZipUtils.ExtractZip"
},
{
  "timestamp": "2017-04-01T23:24:31.8115851Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134240.0,
  "message": "Attempt #2 of 3 on UnzipFileInstallTask.Run -> ZipUtils.ExtractZip"
},
{
  "timestamp": "2017-04-01T23:24:34.8125539Z",
  "level": "Info",
  "thread": 4216,
  "memory": 134240.0,
  "message": "Attempt #3 of 3 on UnzipFileInstallTask.Run -> ZipUtils.ExtractZip"
},
{
  "timestamp": "2017-04-01T23:24:37.8162235Z",
  "level": "Error",
  "thread": 4216,
  "memory": 134448.0,
  "message": "[InstallTaskManager] InstallTask unhandled exception",
  "error": {
    "message": "Could not read C:\\Users\\Ceylina\\AppData\\Local\\Temp\\Curse Client\\4CF5799E232C4E68BD6E532ABEE391D4\\4.zip as a zip file",
    "type": "Ionic.Zip.ZipException",
    "stack": [
      "Curse.Radium.InstallManagement.UnzipFileInstallTask.Run()",
      "Curse.Radium.InstallManagement.BaseInstallTask.RunSynchronously()",
      "Curse.Radium.InstallManagement.BaseInstallTask.RunChild(IInstallTask)",
      "Curse.Radium.InstallManagement.BaseInstallTask.Unzip(FileInfo,DirectoryInfo,String,Nullable`1,Int32)",
      "Curse.Radium.InstallManagement.AddOnInstallTask`1.arP6JKaqmh()",
      "Curse.Radium.InstallManagement.AddOnInstallTask`1.Run()",
      "Curse.Radium.InstallManagement.InstallTaskManager+<>c__DisplayClass37_0.<ProcessQueue>b__0()",
      "Curse.Common.Extensions.TaskEx+<>c__DisplayClass8_0.<TryRun>b__0() in C:\\Projects\\Components\\Repository\\Source\\Curse.Common\\Extensions\\TaskEx.cs:77",
      "System.Threading.Tasks.Task.InnerInvoke()",
      "System.Threading.Tasks.Task.Execute()",
      "System.Threading.Tasks.Task.ExecutionContextCallback(Object)",
      "System.Threading.ExecutionContext.RunInternal(ExecutionContext,ContextCallback,Object,Boolean)",
      "System.Threading.ExecutionContext.Run(ExecutionContext,ContextCallback,Object,Boolean)",
      "System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&)",
      "System.Threading.Tasks.Task.ExecuteEntry(Boolean)",
      "System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()",
      "System.Threading.ThreadPoolWorkQueue.Dispatch()",
      "System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"
    ],
    "innerError": {
      "message": "Cannot read that as a ZipFile",
      "type": "Ionic.Zip.ZipException",
      "stack": [
        "Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile)",
        "Ionic.Zip.ZipFile._InitInstance(String,TextWriter)",
        "Ionic.Zip.ZipFile..ctor(String)"
      ],
      "innerError": {
        "message": "An item with the same key has already been added.",
        "type": "System.ArgumentException",
        "stack": [
          "System.ThrowHelper.ThrowArgumentException(ExceptionResource)",
          "System.Collections.Generic.Dictionary`2.Insert(TKey,TValue,Boolean)",
          "Ionic.Zip.ZipFile.ReadCentralDirectory(ZipFile)",
          "Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile)"
        ]
      }
    }
  }
},
{
  "timestamp": "2017-04-01T23:24:48.748Z",
  "level": "Info",
  "thread": 6996,
  "memory": 134620.0,
  "message": "[UI] Purging memory on blur"

**Comment by nebularg** [comment]
Ah thanks, I think I've figured out the problem

**Comment by ceylina** [comment]
2.0.6 works fine now. Good job fixing it :D
