### ISSUE TITLE
Changing icons on attacks with multiple strikes

### ISSUE THREAD

**Issue by g0urra** [nebularg/Parrot2#2]
### What steps will reproduce the problem?
1.  Choose a class and specialization that have an ability that do multiple strikes, such as Assassination rogue with Mutilate, or Havoc demon hunter with Chaos Strike.
2.  Use Mutilate or Chaos strike on any enemy, which will show multiple strikes, but with an icon different from the ability.
3.  This did not happen in the old version of Parrot, which instead showed the icon of the ability.

Example shown: Chaos Strike's individual strikes not using Chaos Strike's icon.
![Chaos Strike's individual strikes not using Chaos Strike's icon.](https://cloud.githubusercontent.com/assets/12349921/17817395/9a49ec98-663e-11e6-94f2-bbe2b988b88a.jpg)

### What version of Parrot are you using?
v2.0.1

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
The old version was using a function for overriding certain spells' icons with another, such as the ones for Mutilate's attacks with that of Mutilate's.

**Comment by nebularg** [comment]
Didn't realize this was something people would notice/care about, it affected like two spells >.>
