### ISSUE TITLE
Blizzard Combat text not disabling

### ISSUE THREAD

**Issue by cwillms77** [nebularg/Parrot2#24]
### What steps will reproduce the problem?
1.  Log into WoW
2.  Attack something
3.  

### What version of Parrot are you using?
2.0.6

### Do you have an error log of what happened?
No error log

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
enUS client; blizzard combat text is not being disabled by parrot, I need to disable it manually with the below macro

/console floatingCombatTextCombatHealing 0
/console floatingCombatTextCombatDamage 0

**Comment by nebularg** [comment]
Do you have them disabled in options?

![Options](https://camo.githubusercontent.com/c90a6b069f3671484fcfc9e9062eed3fbfb92002/687474703a2f2f692e696d6775722e636f6d2f54314237784f4e2e6a7067)

Unless you have the "Control" option checked, it sets the cvars to their defaults on load.

**Comment by cwillms77** [comment]
That was it, it was disabled by default and I just left it.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kyle Buller <notifications@github.com> Date: 2017-04-21  12:07 AM  (GMT-07:00) To: nebularg/Parrot2 <Parrot2@noreply.github.com> Cc: cwillms77 <cdwillms@icloud.com>, Author <author@noreply.github.com> Subject: Re: [nebularg/Parrot2] Blizzard Combat text not disabling (#24) 
Do you have them disabled in options?

Unless you have the "Control" option checked, it sets the cvars to their defaults on load.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nebularg/Parrot2","title":"nebularg/Parrot2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nebularg/Parrot2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nebularg in #24: Do you have them disabled in options?\r\n\r\n![Options](https://camo.githubusercontent.com/c90a6b069f3671484fcfc9e9062eed3fbfb92002/687474703a2f2f692e696d6775722e636f6d2f54314237784f4e2e6a7067)\r\n\r\nUnless you have the \"Control\" option checked, it sets the cvars to their defaults on load."}],"action":{"name":"View Issue","url":"https://github.com/nebularg/Parrot2/issues/24#issuecomment-296084901"}}}
