### ISSUE TITLE
New feature request: Option to not set critical to sticky but get different animation

### ISSUE THREAD

**Issue by chriszhxi** [nebularg/Parrot2#26]
### What steps will reproduce the problem?
1.  
2.  
3.  

### What version of Parrot are you using?
v2.0.7

### Do you have an error log of what happened?
No.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

Right now we can send critical to sticky, but sticky will overlap normal if set to same anchor point, if set to different anchor point, it takes too much space on screen.

Is it possible to add option that not sending critical to sticky, instead give critical second animation option within normal, like a simple "pow"?

**Comment by nebularg** [comment]
Probably not. You can change the event to remove the sticky flag so everything stacks nicely, but mixing the two into the same block with different effects would require far too much effort.
