### ISSUE TITLE
Shorten Amounts only functions on damage

### ISSUE THREAD

**Issue by genoterril** [nebularg/Parrot2#28]
### What steps will reproduce the problem?
1.  turn on shorten amounts
2.  heal something

(overheal appears to be shortened, but not the actual heal)

### What version of Parrot are you using?
2.0.8 (afaik this was an existing issue in parrot)

**Comment by nene5** [comment]
Same here, Absorbs are not shortened aswell.

**Comment by nebularg** [comment]
I've been meaning to fix this. Several tags don't use the number formatter when building the string.

**Comment by nebularg** [comment]
That should cover everything, let me know if I missed something

**Comment by genoterril** [comment]
Just FYI, it looks like it pushed 2.0.8 again (to Curse, anyway) - but I
grabbed the last changes and it seems to be working.

Many thanks!
