### ISSUE TITLE
Multiple LUA Errors on Startup/Mouseover

### ISSUE THREAD

**Issue by Officedr0ne** [nebularg/Parrot2#30]
### What steps will reproduce the problem?
1.  Login
2.  error pops on startup
3.  

### What version of Parrot are you using?

Latest available

### Do you have an error log of what happened?
Date: 2017-07-02 20:00:04
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Parrot\Data\CombatEvents.lua line 170:
   attempt to call global 'GetSpellTextureFileName' (a nil value)
Debug:
   [C]: GetSpellTextureFileName()
   Parrot\Data\CombatEvents.lua:170: in main chunk
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  NoTaint, v13.01.24
  Swatter, v7.4.5714 (TasmanianThylacine)
  Altoholic, vr182
  Auditor2, v5.0.4
  Bagnon, v7.2.5
  Bartender4, v4.7.7
  BattlePetCount, v1.8.14
  Broker2FuBar, v1.0
  BrokerAuditor, v5.0.4
  BrokerGarrison, v2.0.8.1-5-gc327e38
  Chinchilla, vv2.8.4
  Critline, v4.6.7
  CritlineAuraMonitor, v4.6.7
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMStatusBarTimers, v
  Decursive, v2.7.5.3-1-g6330453
  EasyObliterate, v28
  ElkBuffBars, v2.5.1-189
  Factionizer, v6.02.00.13 16.02.02
  Gnosis, vr184
  HandyNotes, vv1.4.13
  LibSharedMedia30, v3.0-99
  Mapster, v1.7.5
  MasterPlanA, vA
  NomiCakes, v7.2.5.4
  Omen, v3.1.12
  Parrot, vv2.0.4
  TomTom, vv70200-1.0.0
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=426)

Date: 2017-07-02 19:58:24
ID: -1
Error occured in: Global
Count: 1
Message: ..\AddOns\Parrot\Data\Auras.lua line 23:
   attempt to call global 'GetSpellTextureFileName' (a nil value)
Debug:
   ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317:
      ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300
   [C]: GetSpellTextureFileName()
   Parrot\Data\Auras.lua:23: icon()
   Parrot\Code\CombatEvents.lua:2062:
      Parrot\Code\CombatEvents.lua:2020
   Parrot\Code\CombatEvents.lua:2178:
      Parrot\Code\CombatEvents.lua:2175
Locals:
errMsg = "Interface\AddOns\Parrot\Data\Auras.lua:23: attempt to call global 'GetSpellTextureFileName' (a nil value)"
isTSMError = false
tsmErrMsg = nil
AceGUI = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:521
 RegisterWidgetType = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:537
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:613
 Create = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:573
 Release = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @Interface\AddOns\Altoholic\libs\AceGUI-3.0\AceGUI-3.0.lua:247
}
TSM = <table> {
 Operations = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 _author = "Sapu94, Bart39"
 DeleteCustomPriceSource = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Prices.lua:56
 EnableModule = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "TradeSkillMaster"
 IterateEmbeds = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 CreateGroupTree = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\TSMFrames\GroupTree.lua:291
 SecureHookScript = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:410
 GetAuctionPlayer = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\AuctionFrame.lua:45
 RawHookScript = <function> defined @Interface\AddOns\Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:395
 _desc = "Core addon for the TradeSkillMaster suite. Does nothing without modules installed."
 Printf = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Modules.lua:147
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 NO_SOUND_KEY = "TSM_NO_SOUND"
 LDBIcon = <table> {
 }
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 LOG_INFO = <function> defined @Interface\AddOns\TradeSkillMaster\Debug\Logging.lua:376
 Delay = <table> {
 }
 OnTSMDBShutdown = <function> defined @Interface\AddOns\TradeSkillMaster\TradeSkillMaster.lua:411
 operations = <table> {
 }
 RegisterModule = <function> defined @Interface\AddOns\TradeSkillMaster\TradeSkillMaster.lua:339
 toggleBankUI = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\BankUI.lua:307
 ShowConfigError = <function> defined @Interface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:79
 RegisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 LOG_ERR = <function> defined @Interface\AddOns\TradeSkillMaster\Debug\Logging.lua:384
 PrintVersion = <function> defined @Interface\AddOns\TradeSkillMaster\TradeSkillMaster.lua:750
 hooks = <table> {
 }
 getBankTabs = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\BankUI.lua:325
 Groups = <table> {
 }
 UnregisterAllEvents 
AddOns:
  MoncaiCompare, v7.2.0
  NoTaint, v13.01.24
  Swatter, v7.4.5714 (TasmanianThylacine)
  Altoholic, vr182
  Auditor2, v5.0.4
  Babylonian, v5.1.DEV.332(/embedded)
  Bagnon, v7.2.5
  Bartender4, v4.7.7
  BattlePetCount, v1.8.14
  Broker2FuBar, v1.0
  BrokerAuditor, v5.0.4
  BrokerGarrison, v2.0.8.1-5-gc327e38
  Chinchilla, vv2.8.4
  Configator, v5.1.DEV.406(/embedded)
  Critline, v4.6.7
  CritlineAuraMonitor, v4.6.7
  DataStore, vr63
  DataStoreAchievements, vr45
  DataStoreCharacters, vr40
  DataStoreContainers, vr56
  DataStoreCrafts, vr77
  DataStoreCurrencies, vr35
  DataStoreInventory, vr50
  DataStoreMails, vr49
  DataStorePets, vr42
  DataStoreQuests, vr42
  DataStoreReputations, vr40
  DataStoreSpells, vr30
  DataStoreStats, vr29
  DataStoreTalents, vr59
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.5.3-1-g6330453
  EasyObliterate, v28
  ElkBuffBars, v2.5.1-189
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  Factionizer, v6.02.00.13 16.02.02
  Gnosis, vr184
  HaloPro, v(v3.6.3.0)
  HandyNotes, vv1.4.13
  LibExtraTip, v5.12.DEV.423(/embedded)
  LibSharedMedia30, v3.0-99
  Mapster, v1.7.5
  MasterPlanA, vA
  NomiCakes, v7.2.5.4
  Omen, v3.1.12
  OrderHallCommander, v1.4.0-Beta1 70200
  Parrot, vv2.0.4
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlPlayer, v
  PerlTarget, v
  PerlTargetTarget, v
  Postal, vr403
  ProfessionTabs, v1.0.5
  QuestGuru, v2.4.21
  RegularTab, v
  ShadowPriestDoTTimer, v1.8c
  Skada, v1.6.8
  SkadaAvoidanceMitigation, v1.3.4
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  SunnArt, v3.76
  TidyPlates, v6.18.11
  TidyPlatesCleanPlates, v1.9g
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesThreatPlates, v8.4.1
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TimeToDie, vr103
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70200-1.0.0
  TradeSkillMaster, vv3.6.29
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterCrafting, vv3.2.4
  TradeSkillMasterShopping, vv3.4.6
  Viewporter, v
  VuhDo, v3.86
  VuhDoOptions, v3.86
  WorldQuestsList, v36
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=8d2)

**Comment by nebularg** [comment]
Definitely not the "latest available" version. Current version is 2.0.9, you have 2.0.4.

**Comment by Officedr0ne** [comment]
Curse Client is saying 2.0.4 is the latest. So what's the issue? 

[http://imgur.com/a/jAVEb](url)

**Comment by nebularg** [comment]
That looks like the old client? That's probably your issue.

**Comment by nebularg** [comment]
You can try manually installing the latest version from https://mods.curse.com/addons/wow/parrot2. The packager was having an issue with the addon zip for a while, your client might be stuck because of that.
