### ISSUE TITLE
Pls help :c

### ISSUE THREAD

**Issue by Leirax** [nebularg/Parrot2#32]
### What steps will reproduce the problem?
1.  
2.  
3.  

### What version of Parrot are you using?
Newest.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Hey, I love ur addon. But im really annoyed by these "1x-1-xx Crit" numbers and stuff. if i make an ae 
[pls say me how^^.txt](https://github.com/nebularg/Parrot2/files/1346152/pls.say.me.how.txt)
attack as example i see "3 hits- 3 crits" How can i turn that off please?
-Gratz

**Comment by Weenig** [comment]
I am curious to this aswell

**Comment by nebularg** [comment]
I can't edit this for some reason, so I made #47 to remind me
