### ISSUE TITLE
Remove Trigger removes everything from the settings frame until a /reload is performed - the trigger attempted to be removed remains.

### ISSUE THREAD

**Issue by largestherb** [nebularg/Parrot2#4]
### What steps will reproduce the problem?
1.  /parrot
2.  clicking Remove Trigger on a trigger

### What version of Parrot are you using?
v2.0.1-3-g4284ee3

### Do you have an error log of what happened?
nope :(

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
enGB current Live client, using settings from the original Parrot addon.
thought i'd clean up my triggers (they are all disabled and i never use them) and found this happening, thought i'd report it!
thanks for updating parrot though, really couldn't get along with any other sct addon D: !

**Comment by nebularg** [comment]
There, I cleaned them up for you :stuck_out_tongue_winking_eye:
