### ISSUE TITLE
Having issues with Triggers not triggering (Incoming Miss, Block)

### ISSUE THREAD

**Issue by sonicmayhem** [nebularg/Parrot2#40]
### What steps will reproduce the problem?
1.  Create a trigger for Incoming Miss, specifically Block.
2.  No Secondary Condition.
3.  Choose a custom sound (old WoW block sound) and the Shield Block icon.

### What version of Parrot are you using?
v2.0.10-3-g6e61492
v2.0.10
### Do you have an error log of what happened?
Sorry, no. Not sure how to produce a log.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Running World of Warcraft version 7.3.5 (25961) (Release x64) Feb 1 2018 enGB. Tried on my Night Elf Warrior (lvl 101), not sure if that's relevant.

The weird part is when I do the exact same thing but for Parry, with the old parry sound and Icon it works flawless. Every time.

**Comment by nebularg** [comment]
Going through and cleaning up tickets, so sorry if you don't care about this anymore :p

The miss conditions use the SWING_MISSED/SPELL_MISSED event to trigger, and blocking will only result in one if it's a full block (which would likely only happen against an npc)
