### ISSUE TITLE
Error being thrown with latest version

### ISSUE THREAD

**Issue by Gaviin1242** [nebularg/Parrot2#42]
### What steps will reproduce the problem?
1.  Logging in with addon enabled.  Same error shows on multiple toons.

### What version of Parrot are you using?
v2.0.12

### Do you have an error log of what happened?
Message: AceLocale-3.0: Parrot_PointGains: Missing entry for 'The name of the item.'
Time: Thu Jul 19 18:41:35 2018
Count: 1
Stack: AceLocale-3.0: Parrot_PointGains: Missing entry for 'The name of the item.'
Interface\AddOns\Parrot\Data\PointGains.lua:246: in main chunk

Locals: <none>

**Comment by nebularg** [comment]
Thanks, fixed in 8d6b244
