### ISSUE TITLE
Lua Error - Triggers.lua:1377: attempt to index field 'spec' (a nil value)

### ISSUE THREAD

**Issue by azndyna** [nebularg/Parrot2#46]
### What steps will reproduce the problem?
1.  /parrot in chat or trying to load parrot config from Options > Interface > WoW Addons

### What version of Parrot are you using?
Parrot-v2.0.13-7-gc3f34c7

### Do you have an error log of what happened?
Message: Interface\AddOns\Parrot\Code\Triggers.lua:1377: attempt to index field 'spec' (a nil value)
Time: Wed Jul 25 19:01:12 2018
Count: 1
Stack: Interface\AddOns\Parrot\Code\Triggers.lua:1377: attempt to index field 'spec' (a nil value)
Interface\AddOns\Parrot\Code\Triggers.lua:1377: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:371: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:344>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:988: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:984>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1041: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1018>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1703: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1896: in function `Open'
Interface\AddOns\Parrot\Code\Parrot.lua:484: in function <Interface\AddOns\Parrot\Code\Parrot.lua:470>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:813: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...terface\AddOns\Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...sque\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:22: in function <...sque\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: <none>

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

**Comment by nebularg** [comment]
Jeez, how long ago did you play? Can you post your savedvars file?

**Comment by azndyna** [comment]
It's been about a year since I logged in and played. If you're asking how long I've had Parrot, I'm not too sure.

Thanks for working with me on this. If it's too much trouble and the easy solution is to delete my old lua files then I can accept that.

[LUA - Parrot.txt](https://github.com/nebularg/Parrot2/files/2229922/LUA.-.Parrot.txt)

**Comment by nebularg** [comment]
I removed a lot of the upgrade code some while ago, but if people are still getting errors (the original Parrot was mostly working at the start of Legion) I may as well fix them 😝 I'll get this better resolved when I get home tonight

**Comment by azndyna** [comment]
Is this one solution without you making changes - install an older build with the upgrade code, log in, log out, reinstall latest build?

Before making my first thread, I tried to research if anyone currently has the same issue as me, and I didn't see any. If I'm one the only one, or one of a few, I don't mind doing the solution I proposed as long as it's viable.

**Comment by nebularg** [comment]
Finally got around to some coding, should be good now~

**Comment by azndyna** [comment]
Just wanted to give you an update. Hopefully you still get notifications for additional comments after issues have been closed.

I upgraded and received another error, but looked into myself this time since I do Java development and know what it's like trying to fix an issue related to backwards compatibility (if that's how you classify this). 

I added the spec = MAGE attribute to a few triggers (errors guided me to which ones) in the Parrots.lua file and seemed to fix the errors. No errors were thrown throughout the configurations options I went through.
["spec"] = {
		["MAGE"] = "62;63;64",
		},

I wanted to get your opinion if this was an actual solution, or do you think a code fix is required?

**Comment by nebularg** [comment]
Oh I'm dumb, when I copied your saved vars, I only did the Caith UI profile. The problem is the partial settings for removed default triggers. Only changed things get saved back to the file. Currently the code checks if the name is missing to remove the old info, but you went through and deleted the ! at the end of the triggers so the name was saved in the db you 😝
