### ISSUE TITLE
Lua Error: There's already a sink by the short name "Parrot".

### ISSUE THREAD

**Issue by aeger** [nebularg/Parrot2#5]
### What steps will reproduce the problem?
1.  Lua error on login.
2.  
3.  

### What version of Parrot are you using?
2.0.0

### Do you have an error log of what happened?
16x ...rfaceParrot\libs\LibSink-2.0\LibSink-2.0-90103.lua:661: There's already a sink by the short name "Parrot".
[C]: in function `error'
...rfaceParrot\libs\LibSink-2.0\LibSink-2.0-90103.lua:661: in function `RegisterSink'
Parrot\Code\Parrot-v2.0.0.lua:269: in function <Parrot\Code\Parrot.lua:227>

**Comment by nebularg** [comment]
You have another addon registering the "Parrot" sink (probably as a fix for the old Parrot)

**Comment by aeger** [comment]
Found it. It's Omen3

**Comment by nebularg** [comment]
I'll leave this open for now, I'm sure there are other people that have code for that somewhere

**Comment by azaerus** [comment]
Apologies if I'm misunderstanding something here. I have the same error, and am using Omen. Do I need to use a different threat addon, or is there something I can do to fix this?

**Comment by nebularg** [comment]
Sorry, Omen itself has no code to support Parrot. When the LibSink author removed Parrot support, a number of "patches" popped up for various addons that use LibSink to readd Parrot support. You'll have have to search your addons directory for what's adding it.

For example, you can shift-right click -> Open command window here in World of Warcraft/Interface/AddOns and run `findstr /sric:"RegisterSink\(['\"]Parrot" *.lua`

**Comment by azaerus** [comment]
Hey thanks a lot for the help. I appreciate your time. 
Interestingly enough, running the command only found that line in Parrot\Code\Parrot.lua
It's definitely Omen causing the issue though, the error pops up the instant I enable it.

**Comment by nebularg** [comment]
Oh hmm, I see the problem. Any addon that has an old version of LibSink included (like Omen), will still have the Parrot sink registered. If you install LibSink-2.0 itself (so it loads firsts), the problem should stop. I'll see if I can get someone to tag a new version of Omen.

**Comment by azaerus** [comment]
Yep, worked like a charm. Thanks again for your help. Very much appreciated.
