### ISSUE TITLE
Hostility checks broken

### ISSUE THREAD

**Issue by avi90** [nebularg/Parrot2#50]
They are broken because UnitIsFriend() returns true/false now.

ref:
https://github.com/nebularg/Parrot2/blob/16c03be42fa041fa4890910c3122b9f83ef85a09/Data/TriggerConditions.lua#L141-L146

**Comment by nebularg** [comment]
whoops, fixed this then never pushed it 😓

**Comment by avi90** [comment]
who would have thought that 😂 - thanks!
