### ISSUE TITLE
Bug Grabber report

### ISSUE THREAD

**Issue by Yihungdi** [nebularg/Parrot2#51]
### What steps will reproduce the problem?
1.  Turning off/on the add on
2.  
3.  

### What version of Parrot are you using?
Version 2.1.3 I can remove add on and run game with no issues.
Reinstalling the add on and issue returns in addition to the above of what steps 
was taken to reproduce the issue.
### Do you have an error log of what happened?
Yes

### Please provide any additional information below. (example: localization of your client if not enUS or enGB) see attachment Bug Grabber showing incorrect Version: in function  `RegisterSink'
Parrot\Code\Parrot-v2.1.2.lua:287 | in function <Parrot\Code\Parrot.lua:236>
(tail call): ?
[C]: ?[string "safecall Dispatcher[1]"]:9: 
[W0W addon error code for Parrot.txt](https://github.com/nebularg/Parrot2/files/2646974/W0W.addon.error.code.for.Parrot.txt)

**Comment by nebularg** [comment]
This isn’t a problem with Parrot2. You have another addon trying to register the same LibSink name which is causing the error. Do you have both Parrot and Parrot2?

**Comment by Yihungdi** [comment]
Neb,

No I use to have the other Parrot but deleted it.
I may have still had it when I saw Parrot2 and installed it but
I have deleted all references of Parrot and ran CCleaner to clear
Things on my system and then just reinstalled Parrot2.
It’s funny though that when I turn off Parrot2 I don’t get the error.
When I uninstall Parrot2 I don’t get the error.
My concern is why is the error report saying that the error is with
Parrot2 version 2.1.2???

Thanks for looking into this,
G Taylor / Yihungdi

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
