### ISSUE TITLE
Update Parrot2 for Classic

### ISSUE THREAD

**Issue by z7892999** [nebularg/Parrot2#54]
### What steps will reproduce the problem?
1.  
2.  
3.  

### What version of Parrot are you using?
2.1.5

### Do you have an error log of what happened?
132x Parrot\Data\CombatEvents.lua:1931: attempt to call upvalue 'UnitHasVehicleUI' (a nil value)
Parrot\Data\CombatEvents.lua:1931: in function `parse'
Parrot\Code\CombatEvents.lua:2201: in function `?'
Parrot\Code\Parrot-v2.1.5.lua:410: in function <Parrot\Code\Parrot.lua:407>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
InCombatSkipped

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
132x Parrot\Data\CombatEvents.lua:1931: attempt to call upvalue 'UnitHasVehicleUI' (a nil value)
Parrot\Data\CombatEvents.lua:1931: in function `parse'
Parrot\Code\CombatEvents.lua:2201: in function `?'
Parrot\Code\Parrot-v2.1.5.lua:410: in function <Parrot\Code\Parrot.lua:407>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
InCombatSkipped

**Comment by lianmw** [comment]
classic ver plz

**Comment by Cithramir** [comment]
Date: 2019-09-22 15:21:50
ID: 1
Error occured in: Global
Count: 1
Message: ...dOns\Parrot\libs\LibDualSpec-1.0\LibDualSpec-1.0.lua line 74:
   attempt to call global 'GetNumSpecializationsForClassID' (a nil value)
Debug:
   ...dOns\Parrot\libs\LibDualSpec-1.0\LibDualSpec-1.0.lua:74: in main chunk
Locals:
MAJOR = "LibDualSpec-1.0"
MINOR = 17
lib = <table> {
 registry = <table> {
 }
 options = <table> {
 }
 upgrades = <table> {
 }
 currentSpec = 0
 eventFrame = <unnamed> {
 }
 mixin = <table> {
 }
}
minor = nil
registry = <table> {
}
options = <table> {
}
mixin = <table> {
}
upgrades = <table> {
}
AceDB3 = <table> {
 db_registry = <table> {
 }
 frame = <unnamed> {
 }
 New = <function> defined @Interface\AddOns\Bartender4\libs\AceDB-3.0\AceDB-3.0.lua:709
}
AceDBOptions3 = <table> {
 optionTables = <table> {
 }
 handlers = <table> {
 }
 GetOptionsTable = <function> defined @Interface\AddOns\Bartender4\libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:442
}
AceConfigRegistry3 = <table> {
 RegisterOptionsTable = <function> defined @Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:315
 validated = <table> {
 }
 tables = <table> {
 }
 callbacks = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:90
 GetOptionsTable = <function> defined @Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:360
 UnregisterCallback = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:153
 IterateOptionsTables = <function> defined @Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:346
 NotifyChange = <function> defined @Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:289
 ValidateOptionsTable = <function> defined @Interface\AddOns\Bartender4\libs\AceConfig-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:276
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:174
}
_ = "Warlock"
_ = "WARLOCK"
classId = 9
(*temporary) = nil
(*temporary) = 9
(*temporary) = "attempt to call global 'GetNumSpecializationsForClassID' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  Bagnon, v8.2.13
  Bartender4, v4.8.7
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BigWigs, vv3-classic
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  Details, v
  DetailsTinyThreat, v
  GatherMate2, v1.45
  NameplateSCT, v1.17
  OmniCC, v8.2.4
  OneBag3, vv3.3.13
  Parrot, vv2.1.5
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=360)

**Comment by nebularg** [comment]
Just started working on a Classic version, hopefully I'll have something workable in a few days

**Comment by Olorun** [comment]
Yeah would be cool to see it, just so I can finally replace the MSBT quickfix that doesn't show Blizzard ticks on time &&

**Comment by nebularg** [comment]
Pushed a classic alpha to CurseForge https://www.curseforge.com/wow/addons/parrot2/files/2803754

Let me know if anything isn't working correctly

**Comment by chkmyid** [comment]
I was able to modify the Toc to confirm that it is working in the Classic.
However, the config frame could not be called by entering a command.

**Comment by Olorun** [comment]
Classic alpha is working fine so far, but it seems Icons aren't working (at least not for my damaging spells, frostbolt etc)

**Comment by nebularg** [comment]
> I was able to modify the Toc to confirm that it is working in the Classic.
> However, the config frame could not be called by entering a command.

Modify the toc how? Are you sure you were using the classic version?

> Classic alpha is working fine so far, but it seems Icons aren't working (at least not for my damaging spells, frostbolt etc)

Fixed, but the combat log doesn't give the spell id anymore so icons will only show for your abilities

**Comment by chkmyid** [comment]
> Modify the toc how? Are you sure you were using the classic version?

I mean, I downloaded the latest version (v2.1.6) from curse.com and modified it to client version 11302. I can't find a dedicated version yet for the WOW Classic, which was released separately.
We are waiting for a dedicated version of WOW Classic to function normally. ;-)

**Comment by nebularg** [comment]
Pushed a release, so I'm gonna close this now
