### ISSUE TITLE
[Classic] Parrot is trying to load LibDualSpec

### ISSUE THREAD

**Issue by Myrroddin** [nebularg/Parrot2#58]
### What steps will reproduce the problem?
1.  Load the game
2.  Get error

### What version of Parrot are you using?
2.17

### Do you have an error log of what happened?
Yes, I'll edit later. But there is no such thing as dual specialization in Classic, so that lib can be totally removed from Parrot for Classic.

**Comment by nebularg** [comment]
2.17 isn't for classic, sooo
