### ISSUE TITLE
Classic update broke Parrot2

### ISSUE THREAD

**Issue by Olorun** [nebularg/Parrot2#61]
### What steps will reproduce the problem?
1.  Start Classic
2.  
3.  

### What version of Parrot are you using?
v2.1.8-classic1

### Do you have an error log of what happened?
Something got changed with the update, nothing shows up anymore (no damage done, no damage taken, no buffs gained/lost etc)

**Comment by nebularg** [comment]
The TOC changed, are you sure the addon was loaded? (can you open the config)

**Comment by Olorun** [comment]
Yep, it's loaded and config is open.

**Comment by Olorun** [comment]
Found the problem - I had it disabled in PVP.
