### ISSUE TITLE
Money Loot could be locale?

### ISSUE THREAD

**Issue by adavak** [nebularg/Parrot2#7]
very old issues in history.

Parrot\Data\Loot.lua
Code Line:111
"amount", 10000 * gold + 100 * silver + copper

that could be able locale?

suggest

"amount", gold .. L["|cfff0df08Gold|r "] ..  silver .. L["|cffccccccSilver|r "] .. copper .. L["|cffd95439Copper|r"]

like else. :D

**Comment by nebularg** [comment]
Not sure what you're asking. Line 111 just returns a total gold/silver/copper as number. Line 130/134/136 then takes that number and formats the "Amount" value. Are you saying you want the full "Gold", etc instead of  "g"?

**Comment by adavak** [comment]
in CN client. the money loot message like this:

money in mob is 1 gold and 20 silver and 3 coin,
the loot message recived is "loot 12003"

it means 12003 copper............ 
not like normal form.

if my explan not clear. i will be screenshot img after sometimes.

**Comment by nebularg** [comment]
should be 1金20银03铜 hmm

**Comment by adavak** [comment]
in CN client. the money loot message like this:

money in mob is 1 gold and 20 silver and 3 coin,
the loot message recived is "loot 12003"

it means 12003 copper............ 
not like normal form.

if my explan not clear. i will be screenshot img after sometimes.

**Comment by nebularg** [comment]
>.>
