### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by EvenGr1M** [nebularg/Parrot2#70]
Hey, can you please somehow add an option to add a party members outgoing damage text? (Like for example add option for trigger to be able select the source unit of the skill, not the target somehow)

**Comment by nebularg** [comment]
Sorry, this is addon is strictly for tracking your events. If another spell alert addon supports [LibSink-2.0](https://www.curseforge.com/wow/addons/libsink-2-0/relations/dependents), it can output to a Parrot scroll area if you want.
