### ISSUE TITLE
Self-inflicted damage appears both in Incoming and Outgoing

### ISSUE THREAD

**Issue by jcai1** [nebularg/Parrot2#71]
Damage where the source and destination GUID are both the player (e.g. Burning Rush or Eye of Corruption) are shown both in Incoming and Outgoing events. Most people would probably only want this shown under *Incoming* events. However, there is currently no way to achieve this effect.

In fact, even trying to set spell filters manually for each such spell doesn't fix this. Trying to do this would filter the self-damage spell from *both* the Incoming and Outgoing categories, even if only "Outgoing" is checked, because the event counts as both incoming & outgoing on the combat-log level.

**Comment by jcai1** [comment]
Can be accomplished by modifying Data/CombatEvents.lua

add function:

    local function checkPlayerOutOther(srcGUID, _, srcFlags, dstGUID, _, dstFlags)
        return srcGUID == playerGUID and dstGUID ~= playerGUID
    end

then events under Outgoing/Damage category can use `checkPlayerOutOther` instead of `checkPlayerOut`.

**Comment by nebularg** [comment]
I don't think it really needs to be broken up, but but another category for "Self damage" would be good

**Comment by jcai1** [comment]
Agreed, that would avoid the clutter.

I've also realized this also applies to outgoing misses, particularly absorbs (e.g. avoid seeing absorbed Eye of Corruption damage in outgoing as well).

**Comment by nebularg** [comment]
I think I covered everything, try out the alpha build and let me know how it works

**Comment by jcai1** [comment]
(1) Alpha build mostly worked but "self damage absorbs" category wasn't working properly (it got filtered into generic "self damage miss"). I believe this is because

    local function checkPlayerSelfIncAbsorb(srcGUID, _, _, dstGUID, _, _, missType)

has the arg count for a melee damage event. For spell damage it should be

    local function checkPlayerSelfIncAbsorb(srcGUID, _, _, dstGUID, _, _, _, _, _, missType)

Similarly for outgoing.

(2) The latest commit 124da628792543b500a23c6e252f2cda26b18e20 seems to be a regression. It reintroduces the original issue by letting outgoing self-damage count as generic "outgoing damage" again, so it can't be filtered by disabling "outgoing self damage" category.

(3) Finally as a minor sidenote,

    local function checkPlayerSelfInc(srcGUID, _, _, dstGUID)
        return dstGUID == playerGUID and srcGUID == dstGUID
    end
    local function checkPlayerSelfOut(srcGUID, _, _, dstGUID)
        return srcGUID == playerGUID and srcGUID == dstGUID
    end

these are functionally equivalent so only one of them is needed (similarly for checkPlayerSelf[Inc/Out]Absorb, checkPlayerSelf[Inc/Out]Miss).

**Comment by nebularg** [comment]
yep, definitely c/p'd the missType param from SWING_DAMAGE and missed replacing the outgoing check functions in the last commit.

Thanks for looking over it, should be sorted in b850fa4 now

**Comment by jcai1** [comment]
Everything seems to be working fine now. Thanks for the quick fixes.
