### ISSUE TITLE
Tillers reputation hidden for some reason

### ISSUE THREAD

**Issue by Yanngo** [nebularg/Parrot2#77]
### What steps will reproduce the problem?
1.  Do a daily for one of the Tillers faction in Pandaria.
2.  Hand in the quest.
3.  No information about reputation gained in combat text on the screen.

### What version of Parrot are you using?
v2.1.11 (2020-06-03)

### Do you have an error log of what happened?
There are no errors.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB) enGB

Here is a screenshot of the problem. The scrolling combat text area shows only reputation gains with that one individual Tiller while the chat shows both.
https://imgur.com/iwJB4Ky

I've checked whether the problem happens when two reputations are gained: with the faction and with the individual Tiller. I can see no text about reputation gained with Tillers even if only one event is fired.

**Comment by nebularg** [comment]
It wasn't showing because of the bonus text. should be fixed now, thanks~
