### ISSUE TITLE
Killing Machine Rank 2, damage type parsed incorrectly Shadowlands Beta

### ISSUE THREAD

**Issue by Kalrell** [nebularg/Parrot2#79]
Hihi been using Parrot on Beta now addons are enabled and I noticed Parrot is not flagging the Damage type of Obliterate properly.
Shadowlands has added a new passive that changes Obliterate from Physical damage to Frost damage when Killing Machine is proced.
This is registered in the combat log, but Parrot does not appear to parse this as shown in this screenshot:
![km rank 2 parrot addon error](https://user-images.githubusercontent.com/51744515/88462154-1bd19d00-cea1-11ea-9f47-4db3947b2d54.jpg)

### What steps will reproduce the problem?
1.  Log on Beta on a level 58+ Frost deathknight
2.  Auto attack for a Killing Machine proc
3.  Press Obliterate

### What version of Parrot are you using?
2.1.11

### Do you have an error log of what happened?
No 

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Shadowlands Beta Build 35282

**Comment by nebularg** [comment]
Ah, nice catch! Looks like Parrot is using the wrong "school" value

**Comment by nebularg** [comment]
Fixed in c961cf6
