### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by LiNK2088** [nebularg/Parrot2#8]
Error shown upon login in:

Message: Interface\AddOns\Parrot\Code\Parrot.lua:307: attempt to index upvalue 'db' (a nil value)
Time: 09/03/16 10:46:41
Count: 1
Stack: Interface\AddOns\Parrot\Code\Parrot.lua:307: in function `UpdateFCT'
Interface\AddOns\Parrot\Code\Parrot.lua:335: in function <Interface\AddOns\Parrot\Code\Parrot.lua:334>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\BigWigs\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:414: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:995: in function <Interface\FrameXML\UIParent.lua:891>

**Comment by nebularg** [comment]
I'm not entire how that happened or if I can fix it. Does it happen every login? It looks like AceAddon called OnEnable before having run OnInit... which is impossible...
