### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by a268-Beefy** [nebularg/Parrot2#84]
### What steps will reproduce the problem?
I suppose it is something about new honor points looted.

### What version of Parrot are you using?
2.1.11

### Do you have an error log of what happened?
Message: Interface\AddOns\Parrot\Data\PointGains.lua:27: attempt to call global 'GetCurrencyInfo' (a nil value)
Time: Fri Oct 16 18:27:31 2020
Count: 1
Stack: Interface\AddOns\Parrot\Data\PointGains.lua:27: attempt to call global 'GetCurrencyInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Parrot\Data\PointGains.lua"]:27: in function `parse'
[string "@Interface\AddOns\Parrot\Code\CombatEvents.lua"]:2201: in function `?'
[string "@Interface\AddOns\Parrot\Code\Parrot.lua"]:410: in function <Interface\AddOns\Parrot\Code\Parrot.lua:407>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bagnon\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by nebularg** [comment]
Thanks~ I was planning on updating this later today
