### ISSUE TITLE
Will there be a version for TBC Classic?

### ISSUE THREAD

**Issue by DisdainThor** [nebularg/Parrot2#86]
Do you have plans for a TBCC version?

**Comment by nebularg** [comment]
Yup, I'll get it to soon

**Comment by Road-block** [comment]
[Code\Display.lua:491](https://github.com/nebularg/Parrot2/blob/44fba7547e8ee5604f9f70aa88868ddef47f1381/Code/Display.lua#L491) (the flasher code) needs the BackdropTemplateMixin treatment for BCC

**Comment by nebularg** [comment]
Added in d37ab30, thanks
